# Generated by Django 5.2.17 on 2026-10-05 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('maximum_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('margin', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('published_price_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('name_snapshot', models.CharField(blank=True, max_length=120)),
                ('description_snapshot', models.TextField(blank=True)),
                ('duration_days_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_links', to='destinations.destination')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_destinations', to='packages.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='destinations',
            field=models.ManyToManyField(related_name='packages', through='packages.PackageDestination', to='destinations.destination'),
        ),
        migrations.AddConstraint(
            model_name='packagedestination',
            constraint=models.UniqueConstraint(fields=('package', 'destination'), name='unique_package_destination'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_capacity__gt', 0)), name='package_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('margin__gte', 0)), name='package_nonnegative_margin'),
        ),
    ]
