# Generated by Django 5.2.17 on 2026-10-05 14:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booked_price_per_person', models.PositiveIntegerField()),
                ('total_charged', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('submission_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_state', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='packages.package')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('people_count__gt', 0)), name='reservation_positive_people')],
            },
        ),
    ]
